language: scala

jdk: oraclejdk8

scala:
   - 2.11.8
   - 2.12.4
   
jdk:
- oraclejdk8
- oraclejdk9

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.gradle/caches"
  - "$HOME/.sbt/boot/"
  
script:
  - cd $TRAVIS_BUILD_DIR/Stock-Market-Prediction
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm




